#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build_tsup() {
    set -x
    rm -rfv dist
    # npm i tsup --no-save on CI/CD
    npx tsup src/index.ts --format cjs,esm --target es2015 --dts --sourcemap
    cp -fv README.md LICENSE package.json dist
}

commit_lint() {
    if git-branch-is -q -r "^(master)"; then
        commitlint --edit
    else
        true
    fi
}

commit_check() {
    set -x
    from=$(git_last_release_tag)
    commitlint --from $from
}

"$@"
